name: devtalks
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  carousel_slider: ^2.2.1
  google_sign_in: ^4.5.3
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  shared_preferences: ^0.5.10
  cached_network_image: ^2.3.2+1
  firebase_messaging: ^7.0.0
  firestore_ui: ^1.11.0
  url_launcher: ^5.7.2
  confetti: ^0.5.4+1
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Bold.ttf
        - asset: assets/fonts/Metropolis-Regular.ttf

flutter_icons:
  image_path: 'assets/images/DevTalksLogo.png'
  android: true
  ios: true
